### ISSUE TITLE
[Mac] Fail to build Linux and Qemu target on Mac

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1579]
### Description

This is an regression issue and it is blocked weekly test on MacOS. Building linux and qemu target on Mac failed. 

### Test Code

All samples and tests

### Steps to Reproduction

1. Building linux on MAC by command: `make BOARD=linux`
2. Building qemu on MAC by follow instructions: [building-qemu-and-arduino-101-targets](https://github.com/01org/zephyr.js#building-qemu-and-arduino-101-targets)

### Actual Result

1. Building linux target failed on Mac.
<img width="573" alt="screen shot 2017-10-11 at 2 34 10 pm" src="https://user-images.githubusercontent.com/19813546/31425305-4d827348-ae91-11e7-91a7-73df8351abde.png">

2. Building qemu target failed on Mac.
<img width="569" alt="screen shot 2017-10-11 at 2 33 58 pm" src="https://user-images.githubusercontent.com/19813546/31425325-6e40eace-ae91-11e7-9550-ca74f99cf170.png">

 ### Expected Result

Building successfully.
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | a36b2c9 - cd3f44e | qemu & linux | Oct 11, 2017 | Fail
master | 4b77505 | qemu & linux | Oct 11, 2017 | Pass

### Additional Information

This issue is caused by commit a36b2c9.

**Comment by jimmy-huang** [comment]
This is borked by a36b2c90502351f4f8a5e930249ce63c0e0be549, since the it uses the librt timer library which doesn't exists on Mac, only in Linux, @jprestwo

**Comment by jimmy-huang** [comment]
Reverted commit with this patch #1608

**Comment by qiaojingx** [comment]
Verified with commit ce4036c + #1608. Make linux target succeed, but make qemu target still failed.
Qemu:
<img width="1156" alt="screen shot 2017-10-26 at 2 14 22 pm" src="https://user-images.githubusercontent.com/19813546/32037780-82111d70-ba59-11e7-890f-38ddddbedb3e.png">
<img width="1164" alt="screen shot 2017-10-26 at 2 27 06 pm" src="https://user-images.githubusercontent.com/19813546/32037855-cc372796-ba59-11e7-9fe9-960a6c6db119.png">

**Comment by jimmy-huang** [comment]
@qiaojingx I updated patch, but am having problems installing qemu on my mac, can you see if it fixes the build error?

**Comment by qiaojingx** [comment]
Verified with commit cac4c3a + updated #1608 . Unforthnately, make qemu target still failed.

<img width="1067" alt="screen shot 2017-10-27 at 9 38 03 am" src="https://user-images.githubusercontent.com/19813546/32084317-f85baa62-bafa-11e7-8b85-4bea15d245c4.png">

**Comment by jimmy-huang** [comment]
@qiaojingx updated patch

**Comment by qiaojingx** [comment]
Verified with commit 6d751ea + updated #1608 , warnings on Mac are gone, but make qemu target still fails because of `linker error`.
<img width="571" alt="screen shot 2017-10-30 at 10 00 08 am" src="https://user-images.githubusercontent.com/19813546/32151663-9fce60ea-bd59-11e7-8a30-2ce1a10b9e50.png">

**Comment by jimmy-huang** [comment]
@qiaojingx can you open up a separate issue for qemu?  Btw, did you try with the latest instructions on setting up crosstool-ng with 1.9?  http://zephyr-docs.s3-website-us-east-1.amazonaws.com/online/1.9.0/getting_started/installation_mac.html?  I was struggling to get crosstool-ng to build that's why I couldn't test qemu.

**Comment by qiaojingx** [comment]
New issue for qemu is #1631.  I also run into trouble when executing `ct-ng build` by following the latest instructions on setting up cross tool-ng with 1.9.  Issue #1631 is on old cross tool-ng.
