### ISSUE TITLE
[mac] build linux and qemu target failed on Mac

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1669]
### Description

This is an regression issue and it is blocked weekly test on MacOS. Building linux and qemu target on Mac failed. 

### Test Code

All samples and tests

### Steps to Reproduction

1. Building linux on MAC by command: `make BOARD=linux`
2. Building qemu on MAC by follow instructions: [building-qemu-and-arduino-101-targets](https://github.com/01org/zephyr.js#building-qemu-and-arduino-101-targets)

### Actual Result

1. Building linux target failed on Mac.
<img width="568" alt="screen shot 2017-11-20 at 3 53 10 pm" src="https://user-images.githubusercontent.com/19813546/33008193-121ad610-ce0d-11e7-9fb7-3708eece6302.png">

2. Building qemu target failed on Mac.
<img width="440" alt="screen shot 2017-11-20 at 3 57 54 pm" src="https://user-images.githubusercontent.com/19813546/33008203-23282624-ce0d-11e7-8caa-f1cf14ebfbd1.png">

 ### Expected Result

Building successfully.
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 16ad2cf - dcf56a9 | qemu & linux | Nov 20, 2017 | Fail
master | f039536 | qemu & linux | Nov 20, 2017 | Pass

### Additional Information

This issue is caused by commit 16ad2cf.

**Comment by jimmy-huang** [comment]
this shoud be fixed by #1666

**Comment by qiaojingx** [comment]
Verified with commit 58ebd9e. Make linux target succeeds, but make qemu target still fails.
![1](https://user-images.githubusercontent.com/19813546/33161166-9ffd3850-d05c-11e7-9f92-b713e137ca4a.png)
